---
title: "Leaflet_Map_Discharge"
author: "SarahKinz"
date: "7/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(leaflet)
library(sf)
library(raster)
library(dplyr)
library(spData)
library(spDataLarge)
library(tmap)
library(rgdal)
```


Let's create a static map first
```{r}
### reading in and formating discharge data

DEQ_discharge<- read_csv("VDEQ_Springs.csv")

discharge<- DEQ_discharge%>%
  dplyr::select(DEQ_NUMBER, LONGNAD83D, LATNAD83DD,DISCHARGE_GPM)%>%
  filter(DISCHARGE_GPM>=-1)%>%
  group_by(DEQ_NUMBER)%>% 
  summarise(LONGNAD83D, LATNAD83DD, GPM =median(DISCHARGE_GPM))%>%
  distinct()


discharge<- discharge%>%
  mutate(Class= case_when(GPM <= 40 ~ "0-40",
                          GPM > 40 & GPM <=700 ~ "40 - 700",
                          GPM > 700 & GPM <=1400 ~ "700 - 1400",
                          GPM > 1400 ~ "1400-8527"))
  


map_discharge<- st_as_sf(discharge, coords = c("LONGNAD83D","LATNAD83DD"), crs = 4326 )

st_crs(map_discharge)

### Setting the mood... I mean mode

tmap_mode("view")

### Reading in VA shapefile and prepping it

va <- shapefile("VirginiaAdministrativeBoundary.shp/VirginiaCounty.shp")
st_crs(va)

va<-st_as_sf(va)

va<-st_transform(va, crs = 4326)

### reading in the chessy watershed boundary

watersheds <- st_read("Chesapeake_Bay_Watershed_Boundary/Chesapeake_Bay_Watershed_Boundary.shp")

st_crs(watersheds)

watersheds<-st_transform(watersheds, crs = 4326)

sub_basins <- st_read("Chessy_Subbassins/Chesapeake_Bay_Major_Basin_Summary_Groups.shp")

sub_basins<-st_transform(sub_basins, crs = 4326)

test<- map_discharge[sub_basins, ]

### Actually creating the visuals

discharge_map<-
  tm_shape(sub_basins)+
  tm_borders()+
  tm_shape(test)+
  tm_dots("GPM", breaks = c(0,40,700,1400, Inf), size= 0.08, id= "DEQ_NUMBER", title= "Class of Median Discharge (GPM)", palette= "Blues")


  
 # tmap_save(discharge_map, "VA_discharge_map.html")
 
 ### Converting to leaflet format

nhd_wms_url <- "https://basemap.nationalmap.gov/arcgis/services/USGSTopo/MapServer/WmsServer"

test$group= cut(test$GPM,
                breaks = c(0,40,700,1400, Inf), right= FALSE,
                labels = c("0-40 GPM", "40-700 GPM", "700-1400 GPM", ">1400 GPM"))
 

pal = colorFactor(palette = c("aliceblue", "cadetblue1", "cadetblue3", "blue"), domain = test$group)

leaflet(test)%>%
  addTiles()%>%
  addCircleMarkers(color = ~pal(group),
             label= ~ paste0("<br/>DEQ Number: ", DEQ_NUMBER),
             popup = ~paste0("<br/>Category: ",Class, "<br/>Discharge: ", GPM))
 

```


### Messing Around with Layers to Add to the Map
```{r}
chessy_riv_segments<- read_csv("Chesapeake_Bay_Watershed_Model_Phase_6_Land_River_Segments.csv")

# 2058...  Kind of the same thing as the json file, but not spatial... LAME!

delivery_factor<- read_csv("DeliveryFactor_CAST.csv")

### 2049 unique land-river-segments.... Less because 

# general_info <- read_csv("PA_general_info.csv")

test_json<- rgdal::readOGR("CBW_Phase_6_Land_River.geojson")

leaflet(test_json) %>% addTiles()%>% addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0
    )

test_json<-st_as_sf(test_json)

### 2058 land-river-segments

### Verifying that the values for delivery factors are the same across load sources.

delivery_factor_verification<-delivery_factor%>%group_by(LandRiverSegment)%>%
  summarise(Min_Bay=min(RiverToBay_TN_Factor), Max_Bay=max(RiverToBay_TN_Factor), Min_River=min(StreamToRiver_TN_Factor), Max_River=max(StreamToRiver_TN_Factor), Min_Water=min(LandToWater_TN_Factor), Max_Water=max(LandToWater_TN_Factor))%>%dplyr::select(LandRiverSegment, Min_Bay)

all(delivery_factor_verification$Min_Bay == delivery_factor_verification$Max_Bay)

### All of them are the same.


### UPDATE: It did not work out like I thought. In the new object that I created it said I had 2023 objects, which still does not equal the delivery factors that I have. Okay, now comes the fun part. I am going to crop test_json by the CBW shapefile because it is bigger than the CBW.

# test_json<-st_transform(test_json, crs = 4326)
# 
# test<- st_intersection(watersheds, test_json)

### So, let's just try to join the river to bay delivery factors together with their land river segments

segment_with_DF<- full_join(test_json, delivery_factor_verification, by = c("LndRvrSeg" = "LandRiverSegment")) %>% drop_na(Min_Bay)

### Okay, let's make a map now.

bins <- c(0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, Inf)
  
pal<- colorBin("Blues", domain= segment_with_DF$Min_Bay,bins= bins)  

m<- leaflet(segment_with_DF)%>%
  addTiles()%>%
  addPolygons(fillColor = ~ pal(Min_Bay),
              weight = 1,
              smoothFactor =  0.5,
              color = "white",
              fillOpacity = 0.8)%>%
  addLegend(pal = pal, 
              values = ~Min_Bay, opacity = 0.7, 
              title = NULL,
              position = "bottomright")
            

m

labels <- paste

### Let's combine the DF map and the discharge map now.



```


### CONVERTING TO LEAFLET FROM THE CURRENT TMAP   
```{r}

```



#### CODE I MAY USE LATER...
```{r}
  #   tm_layout(main.title = "Discharge (GPM) Volume Distribution of Springs in Virginia",
#             main.title.size = 1,
#             title.position = c("center", "TOP"),
#             legend.position = c("left", "center"))+
# tm_compass(type = "arrow", position = c("right", "top")) +
# tm_scale_bar(position = c("left", "top"))


# tmap_save(discharge_map, "VA_discharge_map.html")
 
### creating map points 








# test<- discharge%>%dplyr::select(LATNAD83DD,LONGNAD83D)
# 
# test$DEQ_NUMBER<- NULL
# 
# points <- SpatialPoints(test, proj4string = CRS("+proj=longlat +datum=WGS84"))

### reading in map data for Virginia

DEQ_springs<- read_csv("VDEQ_Springs.csv")

Map_DEQ_springs<- DEQ_springs%>%dplyr::select(LONGNAD83D, LATNAD83DD)%>%drop_na()

Map_DEQ_springs <- SpatialPoints(Map_DEQ_springs, proj4string = CRS("+proj=longlat +datum=WGS84"))

st_crs(Map_DEQ_springs)

###

va <- shapefile("VirginiaAdministrativeBoundary.shp/VirginiaCounty.shp")
st_crs(va)

va_test <- spTransform(va, CRS(proj4string(Map_DEQ_springs)))
st_crs(va_test)

 

### 
 tm_shape(va_test) +
  tm_borders()+
  tm_shape(Map_DEQ_springs)+
  tm_dots(col = "blue")+
tm_add_legend(type = 'symbol',
              labels = c('USGS', 'VADEQ'),
              col = c('red', 'blue'),
              title = "Spring Type",
              is.portrait = TRUE)+
tm_layout(main.title = "USGS and VDEQ Springs in Virginia",
            main.title.size = 1,
            title.position = c("center", "TOP"),
            legend.position = c("left", "center"))+
tm_compass(type = "arrow", position = c("right", "top")) +
tm_scale_bar(position = c("left", "top"))



```

